version: '3'

services:
  cvs:
    build:
      context: src
      dockerfile: Dockerfile
    environment:
      - CVS_USERNAME=username
      - CVS_PASSWORD=password
    ports:
      - "8080:80"
    volumes:
      - ./:/apache-logs
