name: Compile terms-and-conditions-request lambda
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "lambdas/terms-and-conditions-request/src/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          cd lambdas/terms-and-conditions-request/src
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          cd lambdas/terms-and-conditions-request/src
          pytest --doctest-modules --junitxml=test-results.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: lambdas/terms-and-conditions-request/src/test-results.xml
        if: ${{ always() }}
      - name: Create lambda deployment package
        shell: bash
        run: |
          cd lambdas/terms-and-conditions-request/src
          zip terms-and-conditions-request.zip handler.py
      - name: Copy lambda to s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.DEPLOYMENT_IAM_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEPLOYMENT_IAM_ACCESS_KEY_SECRET }}
          source: './lambdas/terms-and-conditions-request/src/terms-and-conditions-request.zip'
          dest: 's3://rq-arg-lambda-packages-us-east-1'
