name: Compile bonzobazaar-shop lambda
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "lambdas/bonzobazaar-shop/src/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          cd lambdas/bonzobazaar-shop/src
          pip install -r requirements-dev.txt
      - name: Create lambda deployment package
        shell: bash
        run: |
          cd lambdas/bonzobazaar-shop/src
          zip bonzobazaar-shop.zip handler.py
      - name: Copy lambda to s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.DEPLOYMENT_IAM_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEPLOYMENT_IAM_ACCESS_KEY_SECRET }}
          source: './lambdas/bonzobazaar-shop/src/bonzobazaar-shop.zip'
          dest: 's3://rq-arg-lambda-packages-us-east-1'
